// @ts-ignore Generated by `opennextjs-cloudflare build` before Wrangler bundles this entrypoint.
import openNextWorker from "./.open-next/worker.js";
import { RateLimiter as RateLimiterImplementation } from "./worker/rate-limiter";

// Export the class directly from the Worker entrypoint so Wrangler can bind it
// as a Durable Object without depending on re-export resolution.
export class RateLimiter extends RateLimiterImplementation {}

export default openNextWorker;
